# server{
#         listen 80;

#         server_name crm.devolutions.net;
        
#         location /qam/ {
#             proxy_pass http://localhost:801;
#             proxy_set_header Host $host;
#             proxy_set_header X-port $server_port;
#             proxy_set_header X-Real-IP $remote_addr;
#             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#             proxy_set_header X-Forwarded-Proto $scheme;
#         }

#          location / {
#         root C:/nginx-1.27.5/www/SiteA;
#         index index.html;
#         }  
#         location /.well-known/acme-challenge/ {
#         root C:/nginx-1.27.5/www/certbot;
#     }
#     }

        server{
        listen 1560;

        server_name localhost;
        location / {
            root C:/nginx-1.27.5/www/SiteA;
            index index.html;
        }  
        # location /qam {
        #     proxy_pass http://localhost:801;
        #     proxy_set_header Host $host;
        #     proxy_set_header X-port $server_port;
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #     proxy_set_header X-Forwarded-Proto $scheme;
        #  }
        # location /ali {
        #     root C:/nginx-1.27.5/www/SiteB;
        #     index index.html;
        # }  
        
        # root  C:/nginx-1.27.5/www/SiteB;
        # index index.html;
    }

